### ISSUE TITLE
Letters with descents are improperly drawn

### ISSUE THREAD

**Issue by nanokatze** [not-fl3/glium_text_rusttype#3]
![Issue](https://cloud.githubusercontent.com/assets/25141408/25673215/3cc012d4-303f-11e7-839f-491353a760b0.png)
The right set of letters (gjpqy) should be drawn a bit lower with their descents underneath the baseline.

**Comment by not-fl3** [comment]
![2017-05-04-142629_1920x1080_scrot](https://cloud.githubusercontent.com/assets/910977/25701785/84fbe838-30d6-11e7-90d9-2621eb96afde.png)
It seems fixed now! 
https://github.com/not-fl3/glium_text_rusttype/pull/6
