### ISSUE TITLE
White space doesn't have bounding box 

### ISSUE THREAD

**Issue by nanokatze** [not-fl3/glium_text_rusttype#4]
Therefore it isn't being drawn.

Issue happens [here](https://github.com/not-fl3/glium_text_rusttype/blob/master/src/lib.rs#L462), space doesn't have bounding box and code returns None.  Ideas how to fix this?

**Comment by not-fl3** [comment]
@fst3a https://github.com/not-fl3/glium_text_rusttype/pull/5 
Didnt found how to get space pixel width better. And I propose generic solution - every character with no bounding box will have some width based on font_size. At least it works for space :)

**Comment by nanokatze** [comment]
It works well with proportional fonts but apparently not very well with monospace. Though, doing
```
-    let invalid_character_width = font_size / 4;
+    let invalid_character_width = font_size / 2;
```
seems to fix it while doesn't make proportional fonts look bad:

![monospace](https://cloud.githubusercontent.com/assets/25141408/25705415/e16ae4f2-30e5-11e7-846e-756848cf4032.png)
![proportional](https://cloud.githubusercontent.com/assets/25141408/25705410/dea1dc62-30e5-11e7-8ede-6933ab440914.png)

**Comment by not-fl3** [comment]
Agreed, 2 is better than 4. I still didnt found how to do get that size from rusttype, so lets go that way. Closing this issue now.
